<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.7.2</Version>
    <AssemblyVersion>1.7.2</AssemblyVersion>
    <FileVersion>1.7.2</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <Import Project="$(MSBuildThisFileDirectory)..\valheim.targets" />
</Project>